import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model, Types } from 'mongoose';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Tone } from './schemas/tone.schema';
import { ToneInputType } from './tone.service';

export class CreateToneDto {
  @ApiProperty({ example: 'My Coffee Brand Voice' })
  name: string;

  @ApiProperty({ description: 'Full tone prompt generated by the system' })
  tone: string;

  @ApiPropertyOptional({ description: 'Original input used to generate this tone (URL or text prompt)' })
  description?: string;

  @ApiPropertyOptional({ enum: ['analyzed', 'generated', 'custom'], example: 'generated' })
  source?: 'analyzed' | 'generated' | 'custom';
}

export class UpdateToneDto {
  @ApiPropertyOptional({ example: 'My Coffee Brand Voice' })
  name?: string;

  @ApiPropertyOptional({ description: 'Full tone prompt' })
  tone?: string;

  @ApiPropertyOptional()
  description?: string;
}

@Injectable()
export class TonesService {
  constructor(@InjectModel(Tone.name) private toneModel: Model<Tone>) {}

  async create(userId: Types.ObjectId, tenantId: string, dto: CreateToneDto): Promise<Tone> {
    return this.toneModel.create({
      userId,
      tenantId,
      name: dto.name,
      tone: dto.tone,
      description: dto.description ?? '',
      source: dto.source ?? 'custom',
    });
  }

  async findAll(userId: Types.ObjectId, tenantId: string): Promise<Tone[]> {
    return this.toneModel.find({ userId, tenantId }).sort({ createdAt: -1 });
  }

  async findById(id: string, userId: Types.ObjectId, tenantId: string): Promise<Tone | null> {
    return this.toneModel.findOne({ _id: id, userId, tenantId });
  }

  async findByName(name: string, userId: Types.ObjectId, tenantId: string): Promise<Tone | null> {
    return this.toneModel.findOne({ name, userId, tenantId });
  }

  async update(id: string, userId: Types.ObjectId, tenantId: string, dto: UpdateToneDto): Promise<Tone> {
    const tone = await this.toneModel.findOneAndUpdate(
      { _id: id, userId, tenantId },
      { $set: dto },
      { new: true },
    );
    if (!tone) {
      throw new NotFoundException('Tone not found');
    }
    return tone;
  }

  async delete(id: string, userId: Types.ObjectId, tenantId: string): Promise<void> {
    const result = await this.toneModel.findOneAndDelete({ _id: id, userId, tenantId });
    if (!result) {
      throw new NotFoundException('Tone not found');
    }
  }

  sourceFromType(type: ToneInputType): 'analyzed' | 'generated' {
    return type === 'instagram_link' ? 'analyzed' : 'generated';
  }
}
